### ISSUE TITLE
Deprecated function with 2023-04-04a “Jack Jackrum”

### ISSUE THREAD

**Issue by Miro-Collas** [Rainbow-Spike/userhistory#4]
`require(admin.php) is deprecated. It was called from require() in /home/fswiki/public_html/lib/plugins/userhistory/admin.php:5 Autoloading should be used instead!`

**Comment by fiwswe** [comment]
This was fixed in #3.

Unfortunately no new version of the plugin containing the fix has been released yet. :-(

**Comment by Miro-Collas** [comment]
> This was fixed in #3.
> 
> Unfortunately no new version of the plugin containing the fix has been released yet. :-(

Hum.... well, meantime, two suggestions (if you haven't done them already).

- try re-installing, see if that pulls the latest code;
- download the latest code from the code page, uninstall the plugin, install from the downloaded zip. This will give you the latest code, even if the date is still old (though you can edit the date in plugin.info.txt, which is what I did)

**Comment by fiwswe** [comment]
>Hum.... well, meantime, two suggestions (if you haven't done them already).

I simply applied the patch locally. But your solutions might also work.

> try re-installing, see if that pulls the latest code

Yes, in this case that might work because the download link points to the main branch. For the general case (e.g. other plugins) I'd not assume this to work.


>(though you can edit the date in plugin.info.txt, which is what I did)

I tend to avoid editing the version in the local copy. Who knows what confusion that might cause with the Extension Manager? Or when an official update ist released? (Some authors don't use the release date for the version but some other date that might make sense to them. That other date might be before today and then you wouldn't get the official update.)

**Comment by Miro-Collas** [comment]
> I tend to avoid editing the version in the local copy. Who knows what confusion that might cause with the Extension Manager? Or when an official update ist released? (Some authors don't use the release date for the version but some other date that might make sense to them. That other date might be before today and then you wouldn't get the official update.)

Point well made. :-)
